version: '3.3'
services:
  gnache:
    container_name: coupon_dapp_gnache
    build: docker/gnache
    working_dir: /app/CouponDappBackend
    command: ./startup.sh
    ports:
    - "8545:8545"
    volumes:
      - './docker/gnache/startup.sh:/app/CouponDappBackend/startup.sh'
      - './src/contract/dev:/app/CouponDappBackend/build/contracts'
  react:
    container_name: coupon_dapp_react
    tty: true
    build: .
    ports:
    - "3000:3000"
    volumes:
      - '/app/node_modules'
      - '.:/app'
  ipfs:
    container_name: coupon_dapp_ipfs
    build: docker/ipfs
    ports:
    - "5002:5002"